### ISSUE TITLE
[feature] 예산 설정 API

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/budget-management-application#15]
## Issue

* 이슈타입 :  feature
* 해당 기간 별 설정한 예산을 설정합니다. 예산은 카테고리를 필수로 지정합니다.
* REST API

![image](https://github.com/JisooPyo/budget-management-application/assets/130378232/45ad3d8b-7f0b-4231-868f-c7ce3a0be4e5)

## To-do

- [x] 예산 설정 API 구현
- [x] year와 month는 겹칠 수 없습니다.
- [x] 카테고리의 예산을 다 설정하고 합계를 한 달 예산으로 설정합니다.
