### ISSUE TITLE
[feature] 예산 설계 API

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/budget-management-application#17]
## Issue

* 이슈타입 : feature
* 카테고리 별 예산 설정에 어려움이 있는 사용자를 위해 예산 비율 추천 기능이 존재합니다.
* REST API

![image](https://github.com/JisooPyo/budget-management-application/assets/130378232/73d1a044-e653-4fbc-ab71-a967f3892cf0)

## To-do

- [x] 총액을 입력하면, 카테고리 별 예산을 자동 생성합니다.
- [x] 자동 생성된 예산은, 기존 이용중인 유저들이 설정한 평균값입니다.
- [x] 10% 이하의 카테고리는 묶어 기타로 제공합니다.
- [x] 임의의 세 테스트 유저를 만들어 평균 값을 잘 구하는지 테스트합니다.
