### ISSUE TITLE
[feature] 지출 목록 읽기 API

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/budget-management-application#19]
## Issue

* 이슈타입 :  feature
* 필수적으로 `기간` 으로 조회 합니다.
* 조회된 모든 내용의 `지출 합계` , `카테고리 별 지출 합계` 를 같이 반환합니다.
* `합계제외` 처리한 지출은 목록에 포함되지만, 모든 `지출 합계`에서 제외됩니다.
* 특정 `카테고리` 만 조회.
* `최소` , `최대` 금액으로 조회.
* REST API

![image](https://github.com/JisooPyo/budget-management-application/assets/130378232/ae225412-2280-4124-8550-f3dde356c428)

## To-do

- [x] 기간으로 조회
  - [x] 조회된 모든 내용의 지출 합계 - `합계제외`처리한 지출은 제외
  - [x] 카테고리 별 지출 합계 - `합계제외`처리한 지출은 제외
- [x] 기간 + 카테고리로 조회
  - [x] 조회된 모든 내용의 지출 합계 - `합계제외`처리한 지출은 제외
- [x] 기간 + 최소,최대 금액으로 조회
  - [x] 조회된 모든 내용의 지출 합계 - `합계제외`처리한 지출은 제외
  - [x] 카테고리 별 지출 합계 - `합계제외`처리한 지출은 제외
- [x] 기간 + 카테고리 + 최소, 최대 금액으로 조회
  - [x] 조회된 모든 내용의 지출 합계 - `합계제외`처리한 지출은 제외
