### ISSUE TITLE
[feature] 오늘 지출 추천 API

### ISSUE THREAD

**Issue by JisooPyo** [JisooPyo/budget-management-application#23]
## Issue

* 이슈타입 :  feature
* 설정한 월별 예산을 만족하기 위해 오늘 지출 가능한 금액을 총액 과 카테고리 별 금액 으로 제공합니다.

<br>

 * 고려사항 1. 앞선 일자에서 과다 소비하였다 해서 오늘 예산을 극히 줄이는것이 아니라, 이후 일자에 부담을 분배한다.
 * 고려사항 2. 기간 전체 예산을 초과 하더라도 0원 또는 음수 의 예산을 추천받지 않아야 한다.
   * 지속적인 소비 습관을 생성하기 위한 서비스이므로 예산을 초과하더라도 적정한 금액을 추천받아야 합니다.
   * 최소 금액을 자유롭게 설정하세요.

<br>

 * 유저의 상황에 맞는 1 문장의 멘트 노출.
   * 잘 아끼고 있을 때, 적당히 사용 중 일 때, 기준을 넘었을때, 예산을 초과하였을 때 등 유저의 상황에 맞는 메세지를 같이 노출합니다.
 * 15333원 과 같은 값이라면 백원 단위 반올림 등으로 사용자 친화적이게 변환.

<br>

* REST API

![image](https://github.com/JisooPyo/budget-management-application/assets/130378232/f0d99c6a-50d3-4d95-bb8f-119d0d100a8b)

## To-do

- [ ] 15333원과 같은 값이라면 백원 단위 반올림 -> `15300원`
- [x] 카테고리 별 오늘 지출 추천 최소 금액 정하기

![image](https://github.com/JisooPyo/budget-management-application/assets/130378232/3b662896-9df4-4988-8f2f-39553c6bb6b5)

<br>

* 유저의 상황에 맞는 멘트 노출
  * 기준 : 예산 / 그 달의 일수 * 오늘 >= 날짜 1일부터 오늘까지 지출합

- [ ] 잘 아끼고 있다면 "절약을 잘 실천하고 계세요! 오늘도 절약 도전!"
- [ ] 반대라면 "조금만 더 절약하면 목표에 도달할 수 있을 거에요! 화이팅!"
